name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  java-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7

      - name: Run Java tests
        run: ./gradlew check assembleAndroidTest

      - name: SonarQube Analysis
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  android-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7

      - name: Run Android tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          api: 29
          tag: google_apis
          cmd: ./gradlew connectedCheck
